### ISSUE TITLE
Prestashop 1.6/ThirtyBees

### ISSUE THREAD

**Issue by selwynorren** [PayFast/mod-prestashop#2]
Will the updates be made available for Prestashop 1.6/ThirtyBees?

**Comment by bruce-atkinson** [comment]
@selwynorren unfortunately not, only PrestaShop v8.1.0+ is receiving active support.

**Comment by selwynorren** [comment]
Hi Thanks, however ThirtyBees is an active eCommerce System which we have installed for many of our customers. This makes use of the Presatshop 1.6 baseline. I have already tweaked your module to enable the sandbox mode. However does this mean anyone making use of ThirtyBees will no longer be able to use your gateway? Do you perhaps know of any other gateways that do work with ThirtyBees outside of Paystack?

**Comment by bruce-atkinson** [comment]
Hi @selwynorren,

This is unfortunately not supported by https://github.com/Payfast/mod-prestashop. We are not familiar with any other gateways that work with ThirtyBees.
