### ISSUE TITLE
Prestashop 8.1.3 

### ISSUE THREAD

**Issue by armysarge** [PayFast/mod-prestashop#3]
Just wanted to know why orders are not being created in test mode? is this an issue or intentional

**Comment by bruce-atkinson** [comment]
@armysarge, we can confirm that this is not an issue in 8.1.3. Test orders are created when the ITN fires, so your test server does need to be able to receive these responses.

If you would like to discuss this issue further, please [contact the Payfast support team](https://payfast.io/contact/).
